version: '3.9'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=user_service
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/sqls/:/docker-entrypoint-initdb.d/
volumes:
  db:
    driver: local
