service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: "dev"
  region: eu-central-1
  httpApi:
    cors: true

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: post
  get-verification-code:
    handler: app/handler.GetVerificationCode
    events:
      - httpApi:
          path: /verify
          method: get
  create-profile:
    handler: app/handler.CreateProfile
    events:
      - httpApi:
          path: /user
          method: post
  edit-profile:
    handler: app/handler.EditProfile
    events:
      - httpApi:
          path: /user
          method: put
  get-profile:
    handler: app/handler.GetProfile
    events:
      - httpApi:
          path: /user
          method: get
  cart:
    handler: app/handler.Cart
    events:
      - httpApi:
          path: /cart
          method: post
      - httpApi:
          path: /cart
          method: put
      - httpApi:
          path: /cart
          method: get
  payment:
    handler: app/handler.Payment
    events:
      - httpApi:
          path: /payment
          method: post
      - httpApi:
          path: /payment
          method: put
      - httpApi:
          path: /payment
          method: get          

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    watch: true
